name: example-custom-command
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  start:
    # example where instead of forming the default "cypress run ..."
    # the user can specify their own command
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Custom tests 🧪
        uses: ./
        with:
          command: npm run custom-test
          working-directory: examples/custom-command
          config-file: cypress.json

      - name: Show saved file 🖨
        run: cat examples/custom-command/results.json
