name: example-webpack
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  wait:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/webpack
          start: npm start
          wait-on: 'http://localhost:8080'
          config-file: cypress.json
